#!/usr/bin/env python
import locale
import pickle
from pathlib import Path

with open(Path(__file__).resolve().parent / 'tools/pinyin_initial.pkl', 'rb') as f:
    pinyin_initial = pickle.load(f)

def get_acronym(text):
    return "".join(pinyin_initial.get(c, c) for c in text)

def match_input(basename_acronym, entry):
    entry_acronym = get_acronym(entry)
    if entry_acronym == entry:
        return False

    i = j = 0
    while i < len(basename_acronym) and j < len(entry_acronym):
        if entry_acronym[j] == "`":
            end = entry_acronym.index("`", j + 1)
            if basename_acronym[i] in entry_acronym[j+1:end]:
                i += 1
                j = end + 1
                continue
        else:
            if basename_acronym[i] == entry_acronym[j] or basename_acronym[i] == "?":
                i += 1
                j += 1
                continue
        if basename_acronym[i] != entry[i]:
            break
    if i == len(basename_acronym):
        return True

if __name__ == "__main__":
    import sys

    if len(sys.argv) != 3:
        sys.exit(1)

    dironly = sys.argv[1]
    path = Path(sys.argv[2].replace("\\", ""))
    path = path.expanduser()

    entries = [i for i in path.parent.glob('*')]
    if dironly == "x-d":
        entries = [i for i in entries if i.is_dir()]

    entries = [i.name for i in entries if match_input(get_acronym(path.name), i.name)]
    locale.setlocale(locale.LC_ALL, "")
    entries.sort(key=locale.strxfrm)

    for entry in entries:
        print(entry)
